# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_cart_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='archived',
        ),
    ]
