# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_cart_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
